version: '3.8'

services:
  no-fluxo-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: no-fluxo-backend
    # No ports exposed - nginx handles external traffic
    environment:
      - NODE_ENV=production
      - PORT=3325
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3325/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - no-fluxo-network

  nginx:
    image: nginx:alpine
    container_name: no-fluxo-nginx
    ports:
      - "3325:443"   # Main backend HTTPS
      - "4652:4652"  # AI Agent HTTPS  
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/cert.pem:/etc/ssl/certs/cert.pem
      - ./ssl/key.pem:/etc/ssl/private/key.pem
    depends_on:
      - no-fluxo-backend
    restart: unless-stopped
    networks:
      - no-fluxo-network

networks:
  no-fluxo-network:
    driver: bridge 