version: '3.8'

services:
  no-fluxo-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: no-fluxo-backend
    # No ports exposed - nginx handles external traffic
    environment:
      - NODE_ENV=production
      - PORT=3325
    env_file:
      - .env
    volumes:
      # Mount the entire repository for git operations
      - .:/app
      # Mount git config for authentication (if exists)
      - ~/.gitconfig:/home/appuser/.gitconfig:ro
      # Mount SSH keys for git operations (if exists)
      - ~/.ssh:/home/appuser/.ssh:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3325/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - no-fluxo-network

  nginx:
    image: nginx:alpine
    container_name: no-fluxo-nginx
    ports:
      - "80:80"       # HTTP (for redirects)
      - "443:443"     # Main backend HTTPS (standard port)
      - "4652:4652"   # AI Agent HTTPS  
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # Mount your actual Let's Encrypt certificates
      - /etc/letsencrypt/live/no-fluxo-api.shop/fullchain.pem:/etc/ssl/certs/cert.pem:ro
      - /etc/letsencrypt/live/no-fluxo-api.shop/privkey.pem:/etc/ssl/private/key.pem:ro
    depends_on:
      - no-fluxo-backend
    restart: unless-stopped
    networks:
      - no-fluxo-network

networks:
  no-fluxo-network:
    driver: bridge 