version: '3.8'

services:
  no-fluxo-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: no-fluxo-backend
    # No ports exposed - nginx handles external traffic
    environment:
      - NODE_ENV=production
      - PORT=3325
      - PYTHONUNBUFFERED=1  # Ensure Python output is not buffered
      - PYTHONIOENCODING=utf-8  # Set proper encoding for Python output
    env_file:
      - .env
    volumes:
      # Mount the entire repository to enable git operations
      # This allows the monitoring system to fetch updates properly
      - .:/app
      # Use Docker volumes for generated/runtime data to maintain proper permissions
      - fork_data:/app/fork_repo
      - logs_data:/app/logs
      - dist_data:/app/dist
      - python_local:/app/.local
      # Exclude node_modules to prevent conflicts (Docker will use container's version)
      - /app/node_modules
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3325/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - no-fluxo-network

  nginx:
    image: nginx:alpine
    container_name: no-fluxo-nginx
    ports:
      - "80:80"       # HTTP (for redirects)
      - "443:443"     # Main backend HTTPS (standard port)
      - "4652:4652"   # AI Agent HTTPS  
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # Mount your actual Let's Encrypt certificates
      - /etc/letsencrypt/live/no-fluxo-api.shop/fullchain.pem:/etc/ssl/certs/cert.pem:ro
      - /etc/letsencrypt/live/no-fluxo-api.shop/privkey.pem:/etc/ssl/private/key.pem:ro
    depends_on:
      - no-fluxo-backend
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
    networks:
      - no-fluxo-network

networks:
  no-fluxo-network:
    driver: bridge

volumes:
  fork_data:
    driver: local
  logs_data:
    driver: local
  dist_data:
    driver: local
  python_local:
    driver: local 