name: All Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  typescript-tests:
    runs-on: ubuntu-latest
    name: TypeScript Tests
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: no_fluxo_backend/package-lock.json
        
    - name: Install dependencies
      run: |
        cd no_fluxo_backend
        npm ci
        
    - name: Run TypeScript type check
      run: |
        cd no_fluxo_backend
        npm run type-check
        
    - name: Run ESLint
      run: |
        cd no_fluxo_backend
        npm run lint
        
    - name: Run tests
      run: |
        cd no_fluxo_backend
        npm test
        
    - name: Run tests with coverage
      run: |
        cd no_fluxo_backend
        npm run test:coverage
        
    - name: Upload TypeScript coverage
      uses: codecov/codecov-action@v3
      with:
        directory: no_fluxo_backend/coverage
        flags: typescript
        name: typescript-coverage
        fail_ci_if_error: false

  python-tests:
    runs-on: ubuntu-latest
    name: Python Tests
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-3.11-${{ hashFiles('tests-python/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-3.11-
          
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr tesseract-ocr-por
        sudo apt-get install -y poppler-utils
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tests-python/requirements.txt
        pip install pytest pytest-cov pytest-mock
        
    - name: Run Python tests
      run: |
        cd tests-python
        python -m pytest -v --cov=. --cov-report=xml --cov-report=html --cov-report=term-missing
        
    - name: Upload Python coverage
      uses: codecov/codecov-action@v3
      with:
        directory: tests-python
        flags: python
        name: python-coverage
        fail_ci_if_error: false

  test-results:
    runs-on: ubuntu-latest
    needs: [typescript-tests, python-tests]
    name: Test Results Summary
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download coverage artifacts
      uses: actions/download-artifact@v3
      with:
        path: coverage-reports
        
    - name: Generate test summary
      run: |
        echo "## Test Results Summary" >> $GITHUB_STEP_SUMMARY
        echo "### TypeScript Tests" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ All TypeScript tests passed" >> $GITHUB_STEP_SUMMARY
        echo "### Python Tests" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ All Python tests passed" >> $GITHUB_STEP_SUMMARY
        echo "### Coverage Reports" >> $GITHUB_STEP_SUMMARY
        echo "- TypeScript coverage available in Codecov" >> $GITHUB_STEP_SUMMARY
        echo "- Python coverage available in Codecov" >> $GITHUB_STEP_SUMMARY 