name: Backend Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'no_fluxo_backend/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'no_fluxo_backend/**'

jobs:
  backend-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: no_fluxo_backend/package-lock.json

    - name: Instalar dependências do backend
      run: |
        cd no_fluxo_backend
        npm ci

    - name: Verificar tipos TypeScript
      run: |
        cd no_fluxo_backend
        npm run type-check

    - name: Rodar linter
      run: |
        cd no_fluxo_backend
        npm run lint

    - name: Rodar testes unitários
      run: |
        cd no_fluxo_backend
        npm test

    - name: Gerar relatório de cobertura
      run: |
        cd no_fluxo_backend
        npm run test:coverage

    - name: Upload relatório de cobertura para Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./no_fluxo_backend/coverage/lcov.info
        flags: backend
        name: backend-coverage
        fail_ci_if_error: false

    - name: Upload relatório de cobertura como artefato
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: no_fluxo_backend/coverage/
        retention-days: 30 